### ISSUE TITLE
Introduce yourself

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#1]
Hi everyone - 

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other. 

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA.

In addition to this course, I also teach [DGMD E-2](https://hesweb.dev/e2) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. 

More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by vcavallo** [comment]
Hello, I'm Vinney. I'm a freelance, full-stack web developer. I've been freelancing for about four years, mostly building custom web apps for small businesses and startups. Prior to going off on my own I worked at a handful of New York City dev shops and digital agencies.

My girlfriend and I left New York three years ago and moved to a 1750s house near the coast in Rhode Island. No regrets :smiley: (especially mid-pandemic).

The field of AI safety and alignment is deeply enticing to me, but is out of reach without further education (and further degrees) in Computer Science, so I'm here at HES filling in the gaps in my undergrad education and hopefully making myself eligible for a master's program. I'm familiar with Vue and looking forward to honing and formalizing my use and understanding of it.

There's some additional weird stuff about me on the internet on my personal site, [vinneycavallo.com](https://vinneycavallo.com)

I'm looking forward to the course!

P.S. I think the original post in this issue is supposed to be linking to https://hesweb.dev/e2 but is erroneously linking to https://github.com/e2. I'm sure Cezary is appreciating the free profile traffic. :laughing:

**Comment by gboie** [comment]
Hi Everyone! My name is Gabriel Boie and I am beyond exciting to be in this course and learn more about Vue and JavaScript. 

I recently moved to a farm in Northern Virginia as well and adopted bees, horses, geese, guineas and chickens and I am looking forward to combine farm life with some top notch graduate education. 

My biggest passion is polo and while I am still a beginner, I am secretly hoping to win the lottery and dedicate my life to the sport. Until then, I will be here every week coding away!

Looking forward meeting everyone in this class!

**Comment by Ashley877** [comment]
Hi my name is Ashley Hirst. I am looking forward to taking this course I am currently creating a mobile application for my capstone project so I would like to see how this class can help me on the development side of things. My background is in print design so I am looking forward to  expanding my knowledge and skill sets!

Like Gabriel I have a tiny hobby farm in Northern VA. My husband and I just had a baby who will be two months old this upcoming Thursday. Our time is mostly spent on taking care of our animals and baby but that is definitely kept us busy during the pandemic. 

I look forward to the course!

**Comment by tostaylo** [comment]
Hi there,
My name is Torre Taylor and I'm a software developer living in Austin, TX. I am slowly pursuing a Masters's degree from HES and I look to this course to assist with that and help strengthen my perspective of SPA's.  

Software is my career and main hobby, but I do enjoy running outside and playing music daily. Before I worked in software, I owned a fitness coaching business in San Francisco for 12 years.  There are a few more details about me on my personal site, https://tostaylo.github.io.

Kinda jealous of everybody above's farm life. :)

**Comment by adejeffchen** [comment]
Hi there, I'm Jeff Chen. I am a project manager working in California. I am working towards a Master degree in Information Management Systems and I have always wanted to develop a single page application. Looking forward to learn Vue!

**Comment by christian-hilton** [comment]
Hi, I'm Christian.  I'm based in San Francisco, work in software development, and am pursuing the ALM degree in Software Engineering.  I cook and hike a lot in my free time.  I haven't enjoyed JS a lot in the past, but have heard great things about Vue.js, so I'm looking forward to add it to my vocabulary.

**Comment by estanton900** [comment]
Hi, my name is Eva Stanton. I am a designer living and currently working around the Boston area as a freelancer. My background is in both print and digital design and I am taking this class to continue building/updating my skills. Hoping to make the move to development/UX/UI eventually and I believe this will be a great start...Looking forward to the class!

**Comment by ColeDCrawford** [comment]
Hi all, I'm Cole Crawford. I work as a specialist in the Arts and Humanities Research Computing group at Harvard. I help faculty with all sorts of digital projects: digital collections about Celtic folklore, African storytelling, or the vanishing Itelmen language; AR/VR/3D exhibits about the Giza plateau; mixtape makers for the SoundLab; web scraping of fan fiction websites; concept search engines for large text corpora; and more. I also teach workshops on CMSes, Python, data vis, and NLP. I do some side work for the Law School and the Cambridge Encyclopedia of Anthropology. In any remaining free time, I climb (trad, sport, ice), trail run, and travel (pre-quarantimes). I have some previous experience with JS frameworks - mostly React, but also some Angular and recently Svelte. My team has one Vue app that I'll be supporting soon, so looking forward to learning more about that and getting the broader SPA context.

**Comment by yoh514** [comment]
Hello, 
my name is Michelle and I am chiming in from Seoul, South Korea. 

I run a private early learning center for PreK to grade 6 students. And with the COVID situation that we’re going through together, my learning center is temporarily shut down and my teachers and I are doing our best to stay connected with our students. I feel like we are doing relatively okay with the older students but Zoom and some other online content that is available out there is just not organized well enough to manage from parents' and teachers' end.

I do not have any specific plan for the project for this course but I am hoping with support and help from Susan and classmates, I could come up with a helping aid to manage online educational tools for my students.

**Comment by ARuzek** [comment]
Hi, I'm Amelia and I'm from Wisconsin, but living in Peoria, Illinois right now. This is one of my last courses before graduating in the Spring -✨ ALM Digital Media Design✨ 

My story is that I was doing graphic design for a big ecommerce and then got into UI design there. I moved and started working last Spring as a UI designer for a big industrial company but within the first 2 months, they found out I could code things in HTML/CSS/JavaScript (Thanks HES❤️  ) so then I was moved over to do UI development things. There was about a month last summer when I was learning a bunch about Vue, but then the project switched over to web components with LitElement, and I've been building those ever since. Don't get me wrong, I am **in love** with web components, but I feel like I never got a solid foundation in Vue or any other major framework. There are a lot of concepts in the second half of this course that I've never touched before. 

I'm super excited to jump back into it after a year and gain a well rounded understanding of that missing puzzle piece in my web development journey. Oh, also I'm planning to use Vue to build my capstone project. Yay!!😄

**Comment by gabrielajohnson** [comment]
Hi everyone!

I'm Gabby and I am a web content coordinator for J&J medical websites.  I graduated with a BA in Interactive Multimedia from the College of New Jersey and my background is primarily in front-end web development.  I'm in this course because I have always been interested in learning Vue and SPA frameworks in general. I love creating CSS art, drawing and going to the beach.

You can see my web work here: [https://www.gabrielajohnson.com/](https://www.gabrielajohnson.com/)

I host most of my work on codepen: [https://codepen.io/gabrielajohnson/](https://codepen.io/gabrielajohnson/)

Looking forward to getting to know all of you!😄

**Comment by pllealfunes** [comment]
Hi Everyone, 

I'm Paula, and I am working towards the HES Web Technologies Certificate. I became interested in Vue.js after learning about it in CSCIE-3. I found it interesting and felt it would be a valuable skill. I do not come from a technical background, but I do hope to become a Front End Web Developer in the future.

I wish everyone good luck this semester. Thanks! =)

**Comment by R-Elijah** [comment]
Hello hello,

My name is Elijah and I'm a full-time degree candidate with the HES, my concentration is CS of course ;)
I have taken a course with Ms. Buck prior to this (CS E-15) and I recently noticed this course in the catalogue which seemed perfect for continuing on my web development path.

I look forward to a wonderful semester with everyone!

**Comment by ccianelli22** [comment]
Good evening,

My name is Chris and I am a Information Technology Specialist in Washington, D.C. In my job, I write a lot of Python scripts for data manipulation and analytics. To broaden my programming skills, I have been studying JavaScript and have built several React applications. I wanted to take this course to immerse myself in another JavaScript front-end library.

**Comment by aeg224** [comment]
Hi! My name is Alex. I'm a degree candidate in the ALM SWE program and am looking forward to expanding my knowledge of SPA's!

**Comment by LDubya** [comment]
Hi!

I'm Larry from Florida. I'm excited to take this course. I'm mostly self-taught (my bachelors degrees are in Studio Art and Biological Science), and work as a consultant / freelancer in e-commerce. I usually partner w/ agencies that I have a relationship with, but sometimes work directly with businesses owners, directing their internal teams as a management consultant. I've been meaning to learn Vue. This looks like the perfect opportunity. 

Looks like some of us have similar backgrounds! Looking forward to getting to know everyone. 

For some shameless plugs,

- I have a niche note-taking app available on the Mac App Store that helps people take Cornell notes (https://apps.apple.com/us/app/columns-cornell-notes/id1493839821). 
- My blog, STEM Lounge, illustrates the sciences for a more just and sustainable world (https://stemlounge.com). Guest posts are welcome =)

Although the course is remote and asynchronous, I'd love to keep in touch and make it feel as much like a cohort experience as possible. So in addition to Github feel free to connect with me on:

Facebook ( https://www.facebook.com/realLarryWeru )
Linkedin ( https://www.linkedin.com/in/lawrenceweru/ )
Twitter ( http://twitter.com/LarryWeru )

**Comment by michaelkchen13** [comment]
Hi Everyone!

I'm Michael Chen. I am currently working towards a Masters Degree in Digital Media Design here at HES. I graduated with a bachelors degree from The College of New Jersey in Interactive Multimedia and I am also from New Jersey. I currently work as a web content coordinator and have been working on the J&J Medical Devices Website. I am excited to learn more about Website Development through this course. Other then web development I enjoy playing video games and trying new food!

Looking forward to taking the class with everyone!!! :D

**Comment by EricJZell** [comment]
Hello Everyone!
I'm Eric. I'm a software engineer in the Boston area. I'm working towards the Harvard Extension School Programming Certificate. Most of my software experience has been with Ruby, but I am really excited to learn more about JavaScript and SPA's.

**Comment by AdamNgu** [comment]
Hey all,

I’m Adam Nguyen; I’m a web developer based in NYC. I mostly work professionally with React and Angular, so I’m excited to learn Vue and see what the hype is about. This is my first HES class: I’m excited to start! I’m hoping to start my ALM in Software Engineering and am taking this to earn my way in. Looking forward to learning with you all.

Here's my linkedin in case y'all want to connect: https://www.linkedin.com/in/adam-nguyen-91a4b044/

**Comment by sneadthaman** [comment]
Hello E-28,

I'm Sam Janvey and I am currently pursuing a graduate certificate for Web Technologies at HES. I've completed a certificate in Cybersecurity at HES last year and can't seem to get enough!

I am based in Long Island, NY and currently work in distribution of cleaning chemicals and supplies. I'm finally able to give school my undivided attention after a crazy 6 months dealing with COVID and supply chain stresses. I hope to pivot towards a more technical career in development in the near future. After finishing my studies in security, I've come to the realization that I much prefer to build things rather than break them. 

I look forward to learning with everyone and good luck this semester!

**Comment by wtomaszewska** [comment]
Hi everyone, 

I’m Weronika Tomaszewska; I’m a front-end developer based in NYC (moved to the city last year from Poland). I decided to take this course to strengthen my programming skills and learn Vue (I primarily work with React). Excited to begin my HES journey!

Feel free to add me on Linkedin: https://www.linkedin.com/in/wtomaszewska/

**Comment by csloan29** [comment]
Hi class,

I'm Carter Sloan. I'm a software engineer based in Phoenix, AZ. Most of my experience has been with Spring in Java, React, and a little PHP. This is my first class with HES but, if all goes well, I'm looking forward to pursuing my master's in Digital Media Design. I decided to start with this course because I recently started working on some freelance work with my dad that use Vue.js, so I figured this would be a nice to pair that work with this course. 

Outside of programming, I enjoy getting outdoors, going to the gym, playing a little MTG or DnD with friends, and reading Sci-Fi.

Looking forward to learning with everyone!

**Comment by iamakimmer** [comment]
Hey all, 

I'm a full-stack developer based in New York and working towards my master's in Information Systems Management. I primarily work on products in the broadway/arts space. Much of my front end experience has been in Angular 1 and is definitely showing its age. I'm looking forward to using Vue for my future projects. 

Nice to meet everyone!

**Comment by susanBuck** [comment]
Thanks for the introductions, everyone - nice to "virtually" meet you all. : )

**Comment by vmorris412** [comment]
Hi, I'm Valerie! I missed out on this because I was moving across the country last week (from Pittsburgh, PA to the San Francisco Bay Area!) 

I'm a ServiceNow Developer/Consultant working toward a master's in Information Systems Management. I finished my Front End Web Dev certificate in January, and I'm taking this class to further my understanding of single page applications since Angular is heavily relied upon in the ServiceNow Service Portal, and I miss out on projects by only being able to work on the old CMS portals since I don't know Angular. I figured learning Vue would count toward my degree and also get me a step closer to building Service Portals.
