### ISSUE TITLE
Should we use Vue version 3 or version 2 for Project 1?

### ISSUE THREAD

**Issue by iamakimmer** [susanBuck/e28-fall20#15]
Also wondering with the introduction of Vue 3, does this mean that every plugin written in version 2 must be re-written for version 3?

For example, If I needed to use this plugin - https://github.com/samturrell/vue-stripe-payment (just picked a random one), would they have to write it in version 3?

**Comment by aeg224** [comment]
It doesn't look like it. [Here](https://medium.com/better-programming/designing-vue3-plugins-using-provide-and-inject-47b586d9ce4) is an interesting Medium article. To summarize, it states that plugins using Vue 3.0's Composition API will need to be rewritten. However, it is not necessary to use the Composition API, Vue 2's Option API will also work. 

[Here](https://learnvue.co/2019/12/5-things-you-can-do-to-prepare-for-vue-3-0/) is another interesting article on the changes. It looks like a big factor is the addition of Typescript (though I'm not sure why that would cause any issues with Plugins considering it is a superset of JS).

**Comment by susanBuck** [comment]
Good question -

Up to you, but for Project 1, I would recommend v2, just because that's still the "dominant" version I'm covering in lectures/notes. 

A safe bet may be to build it first in v2, then if you have extra time/want an extra challenge make a second iteration adapted to work in v3 (totally optional). 

To be honest, though, Project 1 is a pretty straightforward app so there's not going to be a lot of differences between a v2 and v3 version.

Later in the semester, when we explore Vue 3's Composition API, we'll see a more dramatic shift in style between the two versions - in fact, I was thinking of making that part of Project 3, but it depends on how things progress in the coming month with Vue 3. 

**Speaking to the questions of plugins -** 
Plugins won't necessarily need to be re-written for v3 - the Medium article @aeg224 linked does a good job of explaining why. At minimum though, they will need to be updated to indicate they'd work with/are compatible with version 3. For example, the vue-stripe-payment plugin lists Vue 2 as a dependency: https://github.com/samturrell/vue-stripe-payment/blob/master/package.json#L32

Given this, you'd either have to wait for the plugin author to update, fork and make the update(s) yourself, or find an alternative plugin. : )

**Comment by ColeDCrawford** [comment]
You can still use Typescript with Vue v2, but the Composition API looks like it will have better support.
