### ISSUE TITLE
Private networking is now automatically enabled for DO droplets

### ISSUE THREAD

**Issue by LDubya** [susanBuck/e28-fall20#25]
Hello,

Went to set up a new server today. During the process I saw that private networking is now automatically enabled for DO droplets. Is this something that we should be concerned about for this course? I don't think it will make a difference but just double checking.

<img width="1792" alt="Screen Shot 2020-10-18 at 5 17 21 PM" src="https://user-images.githubusercontent.com/6056426/96386079-2761f680-1166-11eb-9849-ad93d2aa29b4.png">

**Comment by gboie** [comment]
I do not think that would make a difference.

Thanks,
Gabriel

**Comment by susanBuck** [comment]
I agree with @gboie - Won't make a difference for us. 👍

My understanding of it is that if you're using multiple DigitalOcean services (for example, their servers and their databases) - those services can communicate securely with one another, and without incurring additional bandwidth.

It's not relevant to our work because we're only using one DigitalOcean service (their servers).
