### ISSUE TITLE
Folder Document Root issue

### ISSUE THREAD

**Issue by balkasem** [susanBuck/e28-fall20#27]
Hi all, need some help in this issue,

for the point in the requirements that says " **Your project must be set up to run as an independent application with its own document root; it must not run as a subdirectory.** "

Right now you have all of my Project 1 code in the root of e28 repository. It should be in a subdirectory of this repository, e.g. e28/p1.

to resolve it, i would need to structure my folders in local so it has e28/p1, and the index, js, and README files will move to that folder? and that should also be reflected on the Repo in Github, right?

I'm wondering how i would do the pull/deployment to digital ocean server, wouldn't the pull/clone take all the changes to the folder on the server. I'm assuming it won't work, as the pull/clone will clone the whole repository instead of just the e28/p1

would appreciate the help

**Comment by susanBuck** [comment]
> to resolve it, i would need to structure my folders in local so it has e28/p1, and the index, js, and README files will move to that folder? and that should also be reflected on the Repo in Github, right?

This is correct.

You'll create a new directory at `e28/p1/`. 
You'll move any of the p1-related files from the root of `e28` into `e28/p1`.

After moving these files, if you do a `git status` it should recognized the changes/relocation of the files. You can then do your usual git add, commit, push routine to synchronize these changes on Github.

As for your production server - I'm assuming you've already cloned your e28 repository there? If so, you do not want to do another clone. Instead, you'd just do a `git pull` to **update** the e28 repository there so it matches the structure of what is in Github and on your local computer.

One final thing to note as you re-organize your directory structures - you need to update your VirtualHost configs (on production and local) so that your domains for p1 are pointing to the new/correct path (e.g. e28/p1 instead of just e28).

**Comment by gboie** [comment]
Hey Sam,

I do not believe you have to worry about git and directory structure much.
How long your apache configuration points to the right directory you should
be fine.

Thanks,
Gabriel

**Comment by susanBuck** [comment]
@gboie - Technically speaking that is true. But logistically speaking for project specs, we should see projects in directories like `e28/p1`, `e28/p2/` etc.

**Comment by gboie** [comment]
Sorry, I didn't see your initial reply until now. I agree, I assumed that
Sam had the correct directory structure and was having issues rendering the
project1 in the webserver (possible Virtual Host misconfiguration).

**Comment by susanBuck** [comment]
@gboie - No problem! Thanks for contributing your suggestion. 👍

**Comment by balkasem** [comment]
@susanBuck i was able to make it work, thanks for the information
