### ISSUE TITLE
issue with number value

### ISSUE THREAD

**Issue by balkasem** [susanBuck/e28-fall20#28]
hi all,

would appreciate the help in thus error, i pushed the changes for review:

<img width="1440" alt="Screen Shot 2020-10-20 at 12 32 52 AM" src="https://user-images.githubusercontent.com/15233956/96540550-097eb980-126c-11eb-805c-f90b3cb443c8.png">

**Comment by ccianelli22** [comment]
If I understand what you are trying to do correctly I would recommend the following:

1. Remove the script tag for your component or put it in the head of the html. If you remove the script tag, you just need to copy the template, and put it in your component as a template string like shown below. What I believe is happening is that the script tag since its in the body isnt computing until the rendering is completed which is causing your bug. Either of these methods will make your error go away.

![image](https://user-images.githubusercontent.com/70442081/96582919-f68ada00-12a9-11eb-8df6-9c71675984e8.png)

2. Delete your extra round property in your vue instance.

3. At the end of your flip method, update your rounds array with the information you would like to show.

**Comment by susanBuck** [comment]
Piggy-backing on @ccianelli22's notes:

> Remove the script tag for your component or put it in the head of the html. If you remove the script tag, you just need to copy the template, and put it in your component as a template string like shown below. 

I suggest using the script template in the HTML, but as @ccianelli22 noted - it needs to be moved from where it is now. Currently, it's nested within the root Vue instance's template (the div with id of `app`). Refer to my lecture examples where I put the template at the top of the page, right before the div id=app:

![image](https://user-images.githubusercontent.com/237711/96602498-137ed780-12c1-11eb-8ff2-78be2b2b2fdc.png)

Another issue I see:

In your index.html, you have two divs with the id=app, one nested inside the other. The first starts at line 14, and the second starts at line 99. There should only be one div with an id=app - which is the template for your root Vue instance.

**Comment by balkasem** [comment]
still facing an issue when deploying to the server, even though not having that in local pushed the changes, and would appreciate your feedback @susanBuck 
" Vue warn]: Unknown custom element: <round-detail> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>) "

<img width="1440" alt="Screen Shot 2020-10-20 at 1 39 11 PM" src="https://user-images.githubusercontent.com/15233956/96623686-bb080400-12d9-11eb-9292-44b161f226e5.png">

**Comment by balkasem** [comment]
I'm able to see the components in local Vue insepct unlike the server.
@susanBuck 

<img width="1440" alt="Screen Shot 2020-10-20 at 1 41 19 PM" src="https://user-images.githubusercontent.com/15233956/96623856-f86c9180-12d9-11eb-9725-048163ca1e50.png">

**Comment by susanBuck** [comment]
Hi @balkasem - In my test, it appears to work on production without error:

![image](https://user-images.githubusercontent.com/237711/96626604-b1809b00-12dd-11eb-9156-63ea0c66a8d3.png)

Is it still failing on your end?

**Comment by balkasem** [comment]
@susanBuck it's so weird its no reflected on the server for me yet.

**Comment by susanBuck** [comment]
Just to confirm - the URL we're using on production is http://e28p1.sikabalkasem.xyz/ yes? : )

**Comment by balkasem** [comment]
@susanBuck Yes, i tried Safari browser, and it works there; will try to clean the cash in Chrome if that might help get it to work

**Comment by balkasem** [comment]
it seems to work after clearing the chrome cash data @susanBuck thanks for the help

**Comment by susanBuck** [comment]
Glad to hear it's working! 👍
