### ISSUE TITLE
Project 1 share thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-fall20#29]
Hi everyone,

I wanted to start a thread where you all could share your Project 1's and check out what everyone came up with.

In reply to this thread, please share the following:

+ The link to your P1 on production (so everyone can view it)
+ The link to your P1 on Github (so we can see the code behind it)
+ Any notes about your experience building the project. Example:
    + Was there some part you got stuck on? If so, how did you get past the issue?
    + Was there anything you learned in the process of building the app that was new from what we saw in lecture/notes?
    + Was there some aspect of the project/game that you had hoped to tackle but didn't get to?
    + Etc.

**Comment by ccianelli22** [comment]
[P1 project on production](http://e28p1.hesccian.me/)

[P1 github](https://github.com/ccianelli22/e28/tree/master/p1)

**Notes:**

- Since I already had a decent understanding of Vue prior to this class I decided to try out Vue 3 specifically utilizing the Composition API built into Vue 3 which I think is a real game changer. I also implemented the Vue Router into this project as I have not utilized it much prior to this class and found that it is very easy to work with especially compared to React Router used with ReactJS.

- One issue I did have was when building the trivia game, I utilized a free api from [https://opentdb.com/browse.php](https://opentdb.com/browse.php) and some of the formatting that came back was encoded differently, so I had to choose a base64 encoding to receive the data without errors, and then decode it as well, but some characters wont get decoded properly as you may experience in the game.

**Comment by pllealfunes** [comment]
Hey guys, for p1 I reused my Rock Paper Scissors game from our previous homework. I reused my game mostly because I wanted to play it safe for the first project. For future projects I do hope to challenge myself more by coming up with new ideas and creating more complex projects.

P1:  http://e28p1.lefthandedcat.me
Github: https://github.com/pllealfunes/e28/tree/master/p1

**Comment by gboie** [comment]
http://project1.staticquo.io/
https://github.com/gboie/e28/tree/master/project1

"Where in the World is the International Space Station?" guessing game. I am making use of the ISS API that return the Latitude/Longitude and then use that info to call the Google Geo API to translate it in a continent/ocean location. At times the Google API is unable to translate the latitude/longitude in a physical location, but didn't realize that problem until I was done and testing.

**Comment by ARuzek** [comment]
This is my haunted house game. It was fun to make. Originally, I thought I'd make the game birds-eye view and you'd get to choose whether to go up down left right and then I realized that would be a little bit tricky. Also would be cool if there were some strategy involved, but creating a real game with strategy like that is a lot of work, so I just stuck to chance. 
 
http://p1.e28aruzek.me/
https://github.com/ARuzek/e28/tree/master/p1

**Comment by LDubya** [comment]
http://project1.roflmao.me/
https://github.com/LDubya/e28/commit/51a35872d6557590ce872f914506a9e791e2c6df

My original game, Street Referendum, met many of the requirements for this project, so I decided on a direct port. This way I could compare code bases before and after to see where Vue shines.

I already had my data and methods defined separately, and my HTML was already structured modularly, which is all similar to the way you'd do things using Vue. So for the most part I could port my original methods and data variables over, taking the HTML modules and turning those into components, then attaching them to their data and methods the Vue way. So the HTML became a bit more orderly. 

On the JS side, instead of a "toggle" script for toggling DOM elements into and out of view, I attached those toggle-able elements to `v-if`and `v-show`, making the show/hide data-driven and much more intuitive. Since I wasn't using global variables anymore, I did have to use `params` to pass data from parent to child, and `event emitters` to call functions relevant to the parent's data. I also had to make some modifications in order to assign some classnames to the `app` container, since I can't mount a Vue instance to the body. One thing that was cool about Vue was that starting a new round could be as simple as switching a game state variable that causes the game component to re-render, since whenever a component gets rendered the data start again at their default values, ready for a new round. This is as opposed to what I had to do previously -- manually resetting every in-game variable to their default state. Also, separating the game into components forced me to decide which data gets assigned to which component, which made things a bit clearer to understand.

I do still want to make a *Street Referendum October Edition (TM)*, so if I get a minute I'll update it with super cool graphics.

---

#### update October 27:

I had some time last night so here's current progress on the October Edition. Same game mechanics but with updated graphics that leave less to the imagination. Those red squares are supposed to be the two brawlers.

http://streetreferendum.roflmao.me/

**Comment by R-Elijah** [comment]
http://e28p1.mystphy.sx/
https://github.com/R-Elijah/e28/tree/master/p1

Ended up implementing 4-deck BlackJack without splitting instead of the high-low game I did originally. Splitting was actually a solvable problem but it required a refactor for my other functions and I decided to drop it because I already had a minimum viable product I was happy with. The card deck is actually made using unicode which is interesting to me as I was not aware that unicode even had cards. JS also has a pretty meh random number generator and so I implemented a shuffle for an array that made up the deck instead and reshuffle every time 75% of the cards have been dealt.

**Comment by tostaylo** [comment]
[http://e28p1.torretaylor.me/](http://e28p1.torretaylor.me/)
[https://github.com/tostaylo/e28/tree/master/p1](https://github.com/tostaylo/e28/tree/master/p1)

There are some good game projects here 👍 . I went with my original, no-frills, word-guess game.  I come from a React background, and so far, the Vue concepts I've used that differ most from React concepts are ```event emitters``` and ```computed properties```.  I'm looking forward to observing how these Vue concepts will impact how I normally approach component architecture in future, more elaborate, projects.

**Comment by kalbfled** [comment]
https://e28p1.davejk.me
https://github.com/kalbfled/e28/tree/master/p1

This first project, High-Low, was pretty straight-forward for me.  I don't recall running into any problems.

**Comment by gabrielajohnson** [comment]
[http://e28p1.gabrielajohnson.me/](http://e28p1.gabrielajohnson.me/)
[https://github.com/gabrielajohnson/e28/tree/master/p1](https://github.com/gabrielajohnson/e28/tree/master/p1)

I decided to stick with my rock, paper, scissors game.  I added a choice for the user to choose the easy or difficult level, which is based on rock paper scissors expert logic. 

I got stuck on creating the component to display the match history, and it took me a while to figure out how to display the data.  The issue ended up being that I was using camelCase for my variables.  It was just frustrating because I feel like there are so many steps that need to be taken to create a component, save data and display data.  So it was hard to figure out where I went wrong.

**Comment by EricJZell** [comment]
Tic Tac Toe Game: http://e28p1.ericjzell.com/
Code: https://github.com/EricJZell/e28/tree/master/p1

I went with a Tic Tac Toe game. A couple of tricky bugs came up when trying to implement a 'smart pick' for the computer. The root cause of one specific bug came down to 0 being falsey in JavaScript. 

I also attempted to implement the classic snake game in Vue.js, although it still has some bugs:
http://snake.ericjzell.com/
Code: https://github.com/EricJZell/e28/tree/master/snake

One difficulty in that game is determining which element to put the `v-on:keydown` directive on. Ideally, we'd want to listen for keydown events on the entire page, although so far I have been unable to make that work.

**Comment by christian-hilton** [comment]
Hi, here's my mystery word game: http://e28p1.christianh.me

Github: https://github.com/christian-hilton/e28/tree/master/p1

It was overall straightforward to make.  The main problems I ran into were just logistical.  One problem was that Chrome was caching my script.JS file, so for a while I couldn't figure out why my changes weren't working, but then I switched to Firefox for testing and it made more sense!  Another small but time-consuming issue was with the Prod domain setup... When I pasted the VirtualHost text into the Notes app before adding to my default.conf, the quotes were pasted as the wrong type, so I had to troubleshoot for a while before discovering that small change.  In the future, I'd like to spend more time fine tuning the CSS and visuals aspects of the game.

**Comment by estanton900** [comment]
> Here's my Rock Paper Scissors Game.  
> [http://e28p1.evastanton.me/](http://e28p1.evastanton.me/)
> [https://github.com/estanton900/e28/tree/master/project1](https://github.com/estanton900/e28/tree/master/project1)
+ I stuck with my original idea and expanded it a bit. 
+ I enjoyed the challenge and experimenting with using the images as feedback, rather than text.
+ I had a Halloween version planned and was hoping to give the player an option to choose between traditional or halloween but ran out of time before I was able to integrate that piece.

**Comment by ColeDCrawford** [comment]
Blackjack: [https://e28project1.coledcrawford.me/](https://e28project1.coledcrawford.me/)
GitHub: [https://github.com/ColeDCrawford/e28/tree/master/p1](https://github.com/ColeDCrawford/e28/tree/master/p1)

I didn't have time to implement splitting a pair - would require additional game logic, control logic, and presentation changes.

**Comment by aeg224** [comment]
I created a rock paper scissors game. Apart from the dynamic CSS it uses bootstrap for styling and a custom font. 

[Rock Paper Scissors](http://e28p1.alex-giannini.me/)
[GitHub](https://github.com/aeg224/e28/tree/master/p1)

When I first uploaded my project to the production server, I had an issue with the component rendering properly. The problem was similar to the now closed [issue with number value](https://github.com/susanBuck/e28-fall20/issues/28) which was helpful for finding a solution!

**Comment by andymbryant** [comment]
Hello everyone!

I made a simple number guessing game, called Hi-low.

[Link](http://e28p1.vueserver.com/)
[Github](https://github.com/andymbryant/e28/tree/master/p1)

I've worked with Vue before, but never without build tools. So it was a little strange to write JS directly in the HTML, using text/x-templates. But it gave me a deeper understanding of how these systems might function.

Thanks!

**Comment by susanBuck** [comment]
Before I close this thread out, just wanted to say thanks to everyone for sharing their work!
