### ISSUE TITLE
Python3 has a built-in test server

### ISSUE THREAD

**Issue by kalbfled** [susanBuck/e28-fall20#3]
If you have Python3 (or 2) installed on your machine, you can run a test server like this:

```bash
$ cd <your web root>
$ python3 -m http.server
```
[reference](https://docs.python.org/3/library/http.server.html#module-http.server)

**Comment by susanBuck** [comment]
Thanks for sharing @kalbfled! 

We'll explore another "launch via command line" dev server later in the semester that's similar to this as well. 👍

**Comment by ARuzek** [comment]
@kalbfled I've used that before! There are also a bunch of scripts that launch servers available via NPM if you have Node installed, but I'm actually really excited to learn what XAMPP is all about. I feel like every time that I learn a new way to accomplish something, I'm building up my understanding of what's actually happening behind the curtain and connecting the dots with regard to "how things came to be."

**Comment by LDubya** [comment]
I have `Python -m SimpleHTTPServer <port>` in muscle memory by now 😅. Looking forward to picking up XAMPP.

**Comment by gboie** [comment]
Are we still planning on using Digital Ocean for this course? I already created and account and even setup a test droplet and a CI/CD system using Buddy (git to droplet).

**Comment by susanBuck** [comment]
@gboie Yup, we'll use DigitalOcean for our production servers (to be discussed in an upcoming lecture).

The above server options are specific to local development environments.

**Comment by gboie** [comment]
Thank you, also, can I run my test environment on a Droplet as well? I am trying to learn more about the DigitalOcean, it seems to be a great platform.

**Comment by susanBuck** [comment]
@gboie - Yup, it is possible to use a production server as your test/development server. 

I would just recommend having some sort of authorization step in order to access it, otherwise your test/dev work would be publicly accessible, which may not be desirable in a "real world" project.

A common use case for using a public server to view "work in progress" would be having a "staging" version of your application that you could share with clients, etc. for their approval.
