### ISSUE TITLE
my data viz article was trending on Hacker News yesterday

### ISSUE THREAD

**Issue by LDubya** [susanBuck/e28-fall20#36]
Hi all, my article on election map data viz spent yesterday on Hacker News' front page ^_^. If you're a reader, maybe you'll find it interesting?

https://news.ycombinator.com/item?id=24979807

Now I'm trying to figure out how I can turn this into a VueJS project. Any suggestions? It's currently static. I'm thinking maybe an interactive map that can transverse time from earlier elections to the current one could benefit from Vue, but that wouldn't necessarily require a data-driven server backend.

Maybe there's something that requires a server backend that could make it even better?

**Comment by susanBuck** [comment]
This is great - congrats on making it to the front page. : )

re: ideas - I'll throw it out there that if you'd like to adapt the requirements of P2/P3, we could open it up so rather than setting up your own API and requiring read/write functionality, you could tap into data of a publicly available API (here's a bunch on election data: https://blogs.mulesoft.com/dev/api-dev/15-apis-to-track-election-data/) and focus just on read functionality. Not sure if that would be helpful with what you were imaging, but just throwing it out there as an option.

**Comment by susanBuck** [comment]
Saw this post this morning and thought you might appreciate its humor, @LDubya  : )

![image](https://user-images.githubusercontent.com/237711/98263363-b9cf0c00-1f54-11eb-8ea5-4ee4c2deb3af.png)

**Comment by LDubya** [comment]
Yep it's for class. Consuming third party APIs would open up a world of possibilities. Maybe different kinds of visualizations. Could evolve into its own website after this class is finished too. I'll think over this some more and see what ideas pop up ^_^

**Comment by LDubya** [comment]
This is interesting. He's got a static site hosted on Github, pulling from an API to keep the data updated.

https://alex.github.io/nyt-2020-election-scraper/battleground-state-changes.html

**Comment by LDubya** [comment]
One thing I ran into is that some super useful data isn't available in a public API, but people have compiled that data into CSV's and JSON and uploaded them to Github, etc. For the purpose of this project, could we create our own API server that essentially serves required data on request?

**Comment by susanBuck** [comment]
@LDubya - Absolutely.

**Comment by LDubya** [comment]
Awesome! Closing this since I think I have a good idea how to go about it now
