### ISSUE TITLE
Navigate directly to Vue app page other than home?

### ISSUE THREAD

**Issue by kalbfled** [susanBuck/e28-fall20#49]
My Project 2 app is running in production as https://e28p2.davejk.me.  If I click on the "Verifier" menu link, it takes me to that page, as expected.  However, entering https://e28p2.davejk.me/verifier directly into the URL bar yields a 404 error.  Is this expected with Vue Router?

I think the answer is "no" and that the problem results from Apache wanting to serve a file from the directory <web root>/verifier, which does not exist.  I don't know how to tell Apache to send the request to the web root index.

**Comment by susanBuck** [comment]
Hi @kalbfled -

Can you confirm these steps were completed: https://hesweb.dev/e28/notes/vue/vue-router-production 
(Ref: [Week 9, Part 6 video](https://www.youtube.com/embed/YRc6-JpNtIg?rel=0&showinfo=0)) ?

If they weren't, it would explain the behavior you're seeing, as those steps are needed to make it so all URLs route through index.html.

The reason it works on the homepage is because the URL will automatically load /index.html by default. And when you navigate from within the Vue app, it's all doing the navigation via JavaScript.

But when you trigger a new request to https://e28p2.davejk.me/verifier then it looks for a file at /verifier/index.html and fails. 

The above linked config/steps will make it so all traffic routes via /index.html, even if coming from a url such as /verifier.

**Comment by kalbfled** [comment]
I had not added .htaccess, and that was the problem.  Thanks again!

**Comment by susanBuck** [comment]
No prob!
