### ISSUE TITLE
e28-api not updating "Local changes would be overwritten by merge"

### ISSUE THREAD

**Issue by sg7788** [susanBuck/e28-fall20#65]
Hi @susanBuck, 

Was sick the past week, so forgive me for asking this a little late :( I tried to run `bash setup` in my local `e28-api` directory, but I don't see the new "Security Configs" section when I view http://e28-api.loc.  I received the following error after I ran `bash setup`:

![e28-api-bash-setup](https://user-images.githubusercontent.com/55065801/101262990-297d1600-3710-11eb-9057-19161be718cc.png)

Do I need to do anything on my end to get it to work?

Thanks!

**Comment by susanBuck** [comment]
Hi @sg7788 - 

Based on the error output, It's unable to update e28-api/core because it detects there are changed files within that directory; specifically, these files:

+ `routes/api.php`
+ `routes/web.php`

Any chance you made edits to those files? If so, they should not be edited.

To investigate you can run `git diff` on these files to see what the actual changes are. E.g.: from the root of your e28 repository:

```
git diff e28-api/core/routes/api.php
```

```
git diff e28-api/core/routes/routes.php
```

Following that up, you can undo any changes in those files with `git checkout`. E.g.:

```
git checkout e28-api/core/routes/api.php
```

```
git checkout e28-api/core/routes/routes.php
```

That should resolve the merge errors, freeing you to try running `bash setup` again.

Let me know how far the above gets you. : )

**Comment by tostaylo** [comment]
I ran into the same error. You may not want to try what I did to resolve the issue because it does result in losing local data in the database.  I ended up navigating to the ```e28-api/core``` directory with Terminal. Once there I discarded the changes to ```routes/api.php``` and ```routes/web.php``` using ```git checkout --  . ```. This command discards all unstaged changes in the ```e28-api/core``` directory. I then ran ```bash setup``` in the ```e28-api``` directory and everything was updated appropriately. I'm pretty sure I lost everything that was stored in my local database but that wasn't an issue for me.

**Comment by susanBuck** [comment]
@tostaylo - Interesting that you ran into the same problem. I'm trying to figure out what might be triggering edits to routes/api.php and routes/web.php - there shouldn't be anything editing them. Hopefully @sg7788 can share the results of the `git diffs` so we'll have a sense of what is changing. : )

**Re: Losing data in the database** - note that this shouldn't a concern. We're treating our databases as "in development" both locally and on production, which means at any point we can/will reset to them to their default state (i.e. with the seed data).

**Comment by sg7788** [comment]
I ran these in my `e28` directory:
```
git diff e28-api/core/routes/api.php
git diff e28-api/core/routes/web.php
```
But I didn't see anything output in Terminal after I ran those commands.  Then I ran: 
```
git checkout e28-api/core/routes/api.php
git checkout e28-api/core/routes/web.php
```
and I got:
```
error: pathspec 'e28-api/core/routes/api.php' did not match any file(s) known to git
error: pathspec 'e28-api/core/routes/web.php' did not match any file(s) known to git 
```

Then I ran `bash setup` but it's still giving me that same initial error.  I didn't edit these two files, so I'm curious why it's giving me that error?

**Comment by sg7788** [comment]
I also went into the `e28-api/core/` directory and ran `git checkout --` there, like @tostaylo suggested, and I got this:

![image](https://user-images.githubusercontent.com/55065801/101267618-a6b48500-3728-11eb-8cab-fb73d3308295.png)

So I did a `git pull` and then got the same initial error:
```
Updating d2220ee..ee1edc6
error: Your local changes to the following files would be overwritten by merge:
	routes/api.php
	routes/web.php
Please commit your changes or stash them before you merge.
Aborting
```

I've run `bash setup` multiple times when working on ZipFoods and Project 2 in the past, and never encountered any errors or notices then, though.

**Comment by susanBuck** [comment]
@sg7788 - 

Let's try getting rid of `core` completely - the setup script will then rebuild it from scratch.

To do this, first save a backup copy of `core/.env` to maintain any of your existing environment configs.

Then, delete `core`

Then, run bash setup again.
 
If it works, restore `/core/.env` with your backup copy.

That should hopefully get you up and running so you're not being held up by this, and I can come back later and look into the original issue more thoroughly.

**Comment by sg7788** [comment]
Thanks @susanBuck!  I did that and it shows the Security Configs section now :)

**Comment by susanBuck** [comment]
@sg7788 - Glad that did the trick and got you back in working order!

Looking at this more closely/with a fresh set of eyes - 

The issue is related to file permissions and git's tracking of those permissions. 

When we run the bash setup script, it makes a bunch of permission changes to files/directories in `/core`, and those changes are being picked up by git in the `/core` directory.

Was able to recreate on my end:

```
/Applications/XAMPP/xamppfiles/htdocs/test/e28-api/core (master) ! $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/Http/Controllers/GeneratedControllers/.gitignore
	modified:   app/Http/Requests/GeneratedRequests/.gitignore
	modified:   app/Models/GeneratedModels/.gitignore
	modified:   bootstrap/cache/.gitignore
	modified:   database/.gitignore
	modified:   database/factories/GeneratedModels/FavoriteFactory.php
	modified:   database/factories/GeneratedModels/ProductFactory.php
	modified:   database/factories/UserFactory.php
	modified:   database/migrations/2014_10_12_000000_create_users_table.php
	modified:   database/migrations/2014_10_12_100000_create_password_resets_table.php
	modified:   database/migrations/2019_12_14_000001_create_personal_access_tokens_table.php
	modified:   database/migrations/2020_09_08_205700_create_sessions_table.php
	modified:   database/seeders/DatabaseSeeder.php
	modified:   routes/api.php
	modified:   routes/channels.php
	modified:   routes/console.php
	modified:   routes/web.php
	modified:   storage/app/.gitignore
	modified:   storage/app/public/.gitignore
	modified:   storage/framework/.gitignore
	modified:   storage/framework/cache/.gitignore
	modified:   storage/framework/cache/data/.gitignore
	modified:   storage/framework/sessions/.gitignore
	modified:   storage/framework/testing/.gitignore
	modified:   storage/framework/views/.gitignore
	modified:   storage/logs/.gitignore
```

I know on my system I have git configured to globally ignore filemode changes, but it appears the "local" (i.e. project-specific) git config for this repo is defaulting to `true` (causing filemode changes to be tracked).

Not quite sure why that's happening, but am looking into it and will report back when I know more.

**Comment by susanBuck** [comment]
Follow up:

I amended the _setup_ script so it automatically sets the correct filemode setting (_false_). This applies to new installations when "core" is first cloned, as well as existing installs where "core" already exists and is just being updated.

For some insight into this, here's the relevant code:
```bash
# Update e28-api-core if it already exists (`app` directory present)
if [ -d "app" ]; then
    # Toggle filemode tracking to `false` in case it was initially cloned without this setting
    git config --replace-all core.filemode false 

    # Pull down the latest changes
    git pull
# Clone e28-api-core if it does not yet exist
else
    git clone --config core.filemode=false git@github.com:susanBuck/e28-api-core.git .
fi
```

To rectify things so you don't run into this problem again, follow these steps:

1. Update your `setup` script with the [latest changes](https://raw.githubusercontent.com/susanBuck/e28-api/master/setup)
2. Run `bash setup` again

Thanks @sg7788 and @tostaylo for the details/assistance in solving this issue!

**Comment by sg7788** [comment]
Thanks again for looking into this and for the insight!  I updated my `setup` script and ran `bash setup` again.
