### ISSUE TITLE
Cypress Testing - Getting 401 Messages

### ISSUE THREAD

**Issue by pllealfunes** [susanBuck/e28-fall20#72]
Hi @susanBuck,

I have a couple questions relating to the tests I'm making for p3. 

1. I noticed that when I test my account-page.js there is a `/Get 401 /favorite`
 after a user logs in and the user's current favorites doesn't show up. The same message shows up in other tests as well (edit-recipe-page.js, create-page.js, etc.). Everything passes but I feel like that's not good.

2. On the same account-page.js, when the logout button is clicked there's a `POST 401  /logout` message and the user is unable to logout and see the login button again.

<img width="1122" alt="Screen Shot 2020-12-11 at 9 28 30 PM" src="https://user-images.githubusercontent.com/51715816/101970516-e089fd80-3bf8-11eb-917d-5aa21f04c385.png">

I would really appreciate the help. Thanks.

**Comment by susanBuck** [comment]
Hi @pllealfunes -

**re: the 401 request to favorites** - I think what is happening is that after a user logs in, a request is made for favorites. However, Cypress is moving so quickly on to the next testing step, that it abandons the loading of favorites.

If you add another assertion at the end of the test looking for one of the favorite, you won't get the 401 because it will be forced to wait for favorites to finish loading:

```js
 it('lets a user log in and log out', () => {
        cy.visit('/account');
        cy.get('[data-test=test-email-input]').clear().type(user.email);
        cy.get('[data-test=test-password-input]').clear().type(user.password);
        cy.get('[data-test=test-login-button]').click();
        cy.contains('[data-test="test-welcome-message"]', user.name);
        cy.contains('Minced Radish Salad'); // <-- NEW
    })
```

I suspect the second issue you described is a similar scenario, but I have to run out now so I don't have a chance to test for sure. Did want to follow-up with the above info while I had it though! : ) I will reply in more detail either later this evening or Monday.

**Comment by pllealfunes** [comment]
I tried adding the line but the user's favorites still don't show. I still get the `GET 401 /Favorite` and now it also says `Timed out retrying: Expected to find content: 'Minced Radish Salad' but never did.`

**Comment by susanBuck** [comment]
Hi @pllealfunes -

Can you confirm/deny "Minced Radish Salad" is one of the favorites?

If you freshly run setup in your API, it should be as it's part of the seed data (recipe id 1 is attached to user id 1).

If you've been manually using the interface and "un-favorited" it would cause the test to fail.

Here's it passing on my end:

![image](https://user-images.githubusercontent.com/237711/102114752-97a89380-3e08-11eb-98c2-6cd7b6cd3b79.png)

I'm looking at the "lets a user log out" failed test now and will report back shortly.

**Comment by susanBuck** [comment]
The _"lets a user log out"_ test is failing because it assumes the user is already logged in:

```js
it('lets a user log out', () => {

    // This assumes we're already logged in and there's a log out button present...
    cy.get('[data-test=test-logout-button]').click();
    cy.get('[data-test=test-login-button]').should('exist');

})
```

This assumption is likely coming from the fact that the previous test logs the user in. However, login state is not maintained from test to test, because, from the Cypress docs:

> Cypress automatically clears all cookies before each test to prevent state from building up. -[ref](https://docs.cypress.io/api/cypress-api/cookies.html#Syntax).

There are three approaches to address this.

## Approach 1
At the end of the previous test (_lets a user log in and log out_), invoke the following line to have it preserve the cookie/logged in state for the next test.

```js
# Ref: https://docs.cypress.io/api/cypress-api/cookies.html#Preserve-Once
Cypress.Cookies.preserveOnce('laravel_session');
```

This will work, but it's **more ideal to make each of your tests independent from one another**. 

## Approach 2
To keep your tests independent from one another, the _lets a user log out test_ should be responsible for first making sure the user is logged in before attempting the log out.

A somewhat clunky way of doing this is to simply repeat the login steps:

```js
it('lets a user log out', () => {

    // First log the user in...
    cy.visit('/account');
    cy.get('[data-test=test-email-input]').clear().type(user.email);
    cy.get('[data-test=test-password-input]').clear().type(user.password);
    cy.get('[data-test=test-login-button]').click();
    cy.contains('[data-test="test-welcome-message"]', user.name);

    // _Then_ test the log out functionality..
    cy.get('[data-test=test-logout-button]').click();
    cy.get('[data-test=test-login-button]').should('exist');
})
```

Needing to have a user logged in for certain tests is a common need, however, so it's not ideal to have to repeat these log in steps. Given this, a better approach could be to define the log in steps as part of a Cypress[ Custom Command](https://docs.cypress.io/api/cypress-api/custom-commands.html#Syntax).

There's an example of this in the ZipFoods tests here: https://github.com/susanBuck/e28/blob/master/zipfoods/tests/e2e/specs/product-create-page.js#L16

## Approach 3
This final approach piggy-backs on the same idea of Approach 2 - we need a way to conveniently log in a user for certain tests. In Approach 2, we saw ways of doing this via the interface - but this can make our tests flow, because the process of logging in takes time.

A more ideal approach would be set up a special "log in" end point on the API that could be invoked solely for the purposes of testing. E.g.:

```
http://e28-api.yourdomain.loc/login-as/1
# (Where 1 is some specific user id you want to log in as for testing purposes)
# For security purposes, this URL endpoint should only be accessible locally, not on production
```

Your test could then just ping this end point to get automatically logged in, and then proceed...

This latter approach does require adding additional functionality to the API, though, which is not something we have access to. Given this, I would go with Approach 2, but have this Approach in your head in terms of "best practices"

**Comment by pllealfunes** [comment]
I ran bash setup again in my e28-api and I do have 'Minced Radish Salad' as a favorite. I also restarted APACHE, npm run serve, and restarted Cypress.

<img width="1332" alt="Screen Shot 2020-12-14 at 1 16 48 PM" src="https://user-images.githubusercontent.com/51715816/102119309-e78a5900-3e0e-11eb-9bd2-5d209db94cc3.png">

I also added Approach 2 but I still get the 401 for favorite and the `data-test=test-logout-button` says it's not found.

<img width="1440" alt="Screen Shot 2020-12-14 at 1 23 28 PM" src="https://user-images.githubusercontent.com/51715816/102121255-ae071d00-3e11-11eb-800e-6a2919cc1b46.png">

<img width="1440" alt="Screen Shot 2020-12-14 at 1 21 55 PM" src="https://user-images.githubusercontent.com/51715816/102121277-b7908500-3e11-11eb-8b86-ddfa9d185db9.png">

The login button does exist in the HTML. I tried adding double quotes to everything with the words `data-test`, in the testing file and the HTML file, but that didn't help either.
<img width="550" alt="Screen Shot 2020-12-14 at 1 24 20 PM" src="https://user-images.githubusercontent.com/51715816/102121303-c2e3b080-3e11-11eb-8b57-e66776cebe70.png">

The Cypress dashboard says that I'm working on version 3.8.3, could it be that I need to update Cypress?
<img width="797" alt="Screen Shot 2020-12-14 at 1 43 00 PM" src="https://user-images.githubusercontent.com/51715816/102121684-5c12c700-3e12-11eb-9bfd-2b74d3595b8c.png">

NPM mentions a different version.
<img width="541" alt="Screen Shot 2020-12-14 at 1 44 11 PM" src="https://user-images.githubusercontent.com/51715816/102121778-83699400-3e12-11eb-9624-545fb6fc0318.png">

**Comment by susanBuck** [comment]
@pllealfunes - Could you push your latest changes so I can sync up on my end? 

I don't suspect this is a Cypress version issue (but never say never : )

**Comment by pllealfunes** [comment]
Ok, I pushed them up to Github. Thank you so much for the help :)

**Comment by susanBuck** [comment]
Thanks! Taking a look now. : )

**Comment by susanBuck** [comment]
Hm, this is puzzling. Here are my notes after doing another pass:

+ When I run your code exactly as it is from Github, the tests do pass on my end ([screenshot](https://s3.amazonaws.com/screenshots001/2020-12-14-14-33-51.png
)).
+ I am also running Cypress v3.83 (this is the version of Cypress that the Vue testing tools installs).

In Cypress, we see the response to the request to /favorite is returning a 401 error, which means it's getting denied because it lacks the proper authentication. We know log-in is working, because we see "Jill Harvard" on the page, but it's like the _persisting_ of the log-in isn't working since the subsequent request to /favorite fails.

To help debug this...
+ Can you share a screenshot of all of the security configs info output on the top of your API page? (Please include the URL bar showing the URL for the API as part of the screenshot). ([Example](https://s3.amazonaws.com/screenshots001/2020-12-14-14-35-34.png
))
+ In the Chrome window that Cypress is controlling can you open _Web Inspector > Application > Storage > Cookies_ and share a screenshot of what (if any) cookies are in storage after the test as run? ([Example](https://s3.amazonaws.com/screenshots001/2020-12-14-14-33-51.png
))

**Comment by pllealfunes** [comment]
Here is my security configs
<img width="1440" alt="Screen Shot 2020-12-14 at 2 42 54 PM" src="https://user-images.githubusercontent.com/51715816/102129700-cc731580-3e1d-11eb-9150-9660b74b1456.png">

I also noticed that I don't get Chrome window like yours. I only get the following when I run `npm run test:e2e` and click on a test to run. My Cypress GUI also says `Running Electron 78` not `Running Chrome 8` like it shows in the notes. The tests are running on `http://p3.lefthandedcat.loc:8889/account` not `http://p3.lefthandedcat.loc:8888/account`. Maybe that's the issue...not sure why it would be 8889...

<img width="1440" alt="Screen Shot 2020-12-14 at 3 10 59 PM" src="https://user-images.githubusercontent.com/51715816/102130475-eb25dc00-3e1e-11eb-990f-903c45cbdf3d.png">

If I do `"inspect the element"` on the little window where you can watch the tests happen I get the following.

<img width="1440" alt="Screen Shot 2020-12-14 at 3 11 53 PM" src="https://user-images.githubusercontent.com/51715816/102130723-2d4f1d80-3e1f-11eb-85df-30a76e09e583.png">
<img width="1440" alt="Screen Shot 2020-12-14 at 3 12 11 PM" src="https://user-images.githubusercontent.com/51715816/102130732-30e2a480-3e1f-11eb-9e67-f7b220ad0259.png">

**Comment by pllealfunes** [comment]
I went to `http://p3.lefthandedcat.loc:8889/account` in Chrome, I logged in and logged out, and i got the following.


<img width="1440" alt="Screen Shot 2020-12-14 at 3 26 09 PM" src="https://user-images.githubusercontent.com/51715816/102131892-e104dd00-3e20-11eb-9547-7d82c0801e3b.png">

<img width="1440" alt="Screen Shot 2020-12-14 at 3 27 50 PM" src="https://user-images.githubusercontent.com/51715816/102131978-02fe5f80-3e21-11eb-901a-d93f6ea50162.png">

**Comment by susanBuck** [comment]
> The tests are running on http://p3.lefthandedcat.loc:8889/account not http://p3.lefthandedcat.loc:8888/account. Maybe that's the issue...not sure why it would be 8889...

It would be 8889 if you already had the app running and it was using port 8888. 

And I agree that's likely the root of the issue.

Try opening e28-api/core/.env and updating the stateful domains to a wildcard `*`:

```
SANCTUM_STATEFUL_DOMAINS=*
```

This way, the API will return login cookies for any domain you're testing from (just as long as it's on the same primary domain that the API is running on).

**Comment by pllealfunes** [comment]
I was able to get it working. I'm sorry I didn't know I wasn't supposed to have it running while performing the tests. Thank you so much for all the help.
