### ISSUE TITLE
Mixed Content Error on production

### ISSUE THREAD

**Issue by gabrielajohnson** [susanBuck/e28-fall20#77]
I am getting a Mixed Content error in the console on production:

_Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS._

App: https://e28p3.gabrielajohnson.me/
API: https://e28-api.gabrielajohnson.me/

Both urls appear to be secure and on https, and my p3 .env.production file has the url set to VUE_APP_API_URL=https://e28-api.gabrielajohnson.me.  I'm not sure what other changes I need to make so that it fetches to the API.

**Comment by LDubya** [comment]
Hi Gabriela,

Looking at the raw dist js (https://github.com/gabrielajohnson/e28/blob/master/p3/dist/js/app.8645fe25.js) it's definitely outputting `http://e28-api.gabrielajohnson.me` for `process.env.VUE_APP_API_URL` when built. Looks like the `process.env.VUE_APP_API_URL` environment variable is resolving to `http://e28-api.gabrielajohnson.me` instead of `https://e28-api.gabrielajohnson.me`.

I've been using my own API to date so far, so can't offer any more specific help unfortunately, but I think this may come down to figuring out where it's getting `http://e28-api.gabrielajohnson.me` from

**Comment by LDubya** [comment]
Hi Gabriela,

Are you building locally first and then deploying, or building on the server?

If you're building locally and then deploying to production, it looks like your ` process.env.VUE_APP_API_URL` environment variable is still resolving to `http://e28-api.gabrielajohnson.me`, which shows up in your `/dist` app.js file (https://github.com/gabrielajohnson/e28/blob/db4cd2c79634b7934a857710eb447ab0d47cc747/p3/dist/js/app.8645fe25.js). 

Have you rebuilt (`npm run build`) before deploying? If so, try to see where `http://e28-api.gabrielajohnson.me` may be coming from.

If you're building on the server, maybe you need to do an `npm run build` after the `git pull`?

**Comment by susanBuck** [comment]
Confirming @LDubya's response!

**Comment by gabrielajohnson** [comment]
@LDubya Thank you for your response! Building it in my local with the updated .env file was what worked for me!

**Comment by LDubya** [comment]
No problem, best of luck w/ the rest of your studies =)
