### ISSUE TITLE
Console error: Uncaught ReferenceError: key is not defined (but only on JSFiddle)

### ISSUE THREAD

**Issue by ARuzek** [susanBuck/e28-fall20#8]
I have events in my game, and my events are added through an `addEventListener` pointing to the appropriate function to fire. 

**relevant code:** 
```js
document.addEventListener("keyup", movePerson);
let personLocation = 0;
function movePerson() {
  if (key == "ArrowLeft") {
// blah blah blah etc...
```
This works perfectly well while developing locally and viewing on server. However, when I copy and paste the game into the JSFiddle I get the console error:  `Uncaught ReferenceError: key is not defined`

I'm able to correct this error by adding an "event" keyword `if(event.key == "ArrowLeft") { ` but locally on my VSCode if I do the same, it gives me the opposite error of: 
```md
var event: Event
@deprecated

'event' is deprecatedts(6385)
No quick fixes available
```
Is it ok to submit the game both ways? Is JSFiddle just using older JavaScript syntax to check things? 

(full code available on JSFiddle here https://jsfiddle.net/aruzek/awfpund6/15/ or on github here: https://github.com/ARuzek/e28)

**Comment by ccianelli22** [comment]
Could it be your browser? I just tried it within JSFiddle and did not receive any errors while testing your game. I am using Chrome.

**Comment by ARuzek** [comment]
@ccianelli22  That link is the link with the event keyword. This is a link without the event keyword: https://jsfiddle.net/aruzek/awfpund6/16/

**Comment by ccianelli22** [comment]
So in both [https://jsfiddle.net/aruzek/awfpund6/16/ ](https://jsfiddle.net/aruzek/awfpund6/16/ ) and [https://jsfiddle.net/aruzek/awfpund6/15/](https://jsfiddle.net/aruzek/awfpund6/15/) I noticed that the event handlers that you created were missing the event parameter. In your functions where you call `preventDefault()` it was giving me an error as not defined and that is because `preventDefault()` is a method from the event object. For instance from your code above:

```JavaScript
document.addEventListener("keyup", movePerson);
let personLocation = 0;
function movePerson() {
  if (key == "ArrowLeft") {
// blah blah blah etc...
```

`movePerson()` is the event handler and should take the event as a paramater in the function like so. I used object destructuring but you could also pass event and then use event.key and event.code

```JavaScript
document.addEventListener("keyup", movePerson);
let personLocation = 0;
function movePerson( {key, code }) {
  if (key == "ArrowLeft") {
// blah blah blah etc...
```
If you pass the event object within all of your event handlers it should be fine.

Hope this helps

**Comment by ARuzek** [comment]
Thanks, I'll pass an event object and name it something other than "event" since that has a special meaning. 

**solution:** 
```js
function movePerson(whenTheyUseKeyboard) {
  if (whenTheyUseKeyboard.key == "ArrowLeft") {
```
